### PR TITLE
Use USB polling instead of IRQs to avoid intermediate vector table

### PR DESCRIPTION
**Pull request by Squonk42**
It will make things easier to move the HID bootloader to high memory if we don't have to create an intermediate vector table just to have an USB IRQ handler, and we don't have much to do beside blinking the LED anyway.

### CODE REVIEW

**Comment by Squonk42** [comment]
Hi Vassilis,

Could you re-generate the CLI binaries for Windows and Mac, I have Linux only?

The F4 version will also require to be reworked to put it into high-memory too.

**Comment by Squonk42** [comment]
Also, Roger ifound that the Mac binary was not executable. I already fixed this for Linux, but could you fix it for the Mac at the same time, please?

**Comment by uzi18** [comment]
Why you want to force everyone to use High mem for bootloader?

**Comment by Serasidis** [comment]
> The F4 version will also require to be reworked to put it into high-memory too.
I revert the previous HID-BL version because we first need to talk about what we want from this Bootloader for all MCU devices that we want to support and how to handle the best code strategy to do that.

For example, the F40x and F41x devices have 128kB at the last sector. That means, we sacrifice a lot of flash memory for the bootloader.

**Pull request merged**
